// File 1: app/layout.js
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Navbar } from "./components/Navbar.jsx";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Navbar />
        {children}
           <footer className="bg-gray-900 text-white py-8 mt-0">
        <div className="container mx-auto px-4 text-center">
          <p className="text-sm mb-4">
            © 2025 Zeyad Maher. All rights reserved.
          </p>
          <div className="flex flex-col sm:flex-row justify-center items-center space-y-2 sm:space-y-0 sm:space-x-6">
            <a
              href="#"
              className="hover:text-yellow-400 transition duration-300 text-sm font-medium"
            >
              Privacy Policy
            </a>
            <a
              href="#"
              className="hover:text-yellow-400 transition duration-300 text-sm font-medium"
            >
              Terms of Service
            </a>
            <a
              href="#"
              className="hover:text-yellow-400 transition duration-300 text-sm font-medium"
            >
              Contact
            </a>
          </div>
        </div>
      </footer>
      </body>
    </html>
  );
}